name: Manual Lambda

on: workflow_dispatch

jobs:
  build:
    runs-on:
      - codebuild-gha-runners-lambda-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: sleep
        run: sleep 60
